# Generated by Django 4.0 on 2022-01-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=100)),
                ('TaskDescription', models.CharField(max_length=400)),
            ],
        ),
    ]
