# Generated by Django 4.0 on 2022-01-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='sal',
            field=models.IntegerField(default=1),
        ),
    ]
