# Generated by Django 4.0 on 2022-02-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_alter_tasks_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Confirm_Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
