# Generated by Django 4.0.2 on 2022-02-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResultData',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
                ('Maths', models.FloatField(max_length=100)),
                ('History', models.FloatField(max_length=100)),
                ('Geography', models.FloatField(max_length=100)),
                ('English', models.FloatField(max_length=100)),
                ('Civics', models.FloatField(max_length=100)),
                ('Economics', models.FloatField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
