# Generated by Django 4.0.2 on 2022-02-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresultdata',
            name='Chance_Given',
            field=models.IntegerField(default=0),
        ),
    ]
